### PR TITLE
Gitbook conversion

### PR DESCRIPTION
**Pull request by Shy**
Converting from a Jekyll Site to a gitbook for readability. This also separates each chapter out for easier editing and management. 

You can view the book here: 
https://shy.gitbooks.io/hackathon-organizer-guide/content/introduction.html

Once merged we'll need to update the guide.mlh.io domain to point to gitbooks output.

### CODE REVIEW

**Comment by theycallmeswift** [comment]
Looks much better.

 - Logo should be the lockup
 - The video on sponsorship is broken
https://www.dropbox.com/s/ao03mofz9ul9yc7/Screenshot%202016-03-16%2018.04.28.png?dl=0


On Wed, Mar 16, 2016 at 3:26 PM, Shy Ruparel <notifications@github.com>
wrote:

> Converting from a Jekyll Site to a gitbook for readability. This also
> separates each chapter out for easier editing and management.
>
> You can view the book here:
> https://shy.gitbooks.io/hackathon-organizer-guide/content/introduction.html
>
> Once merged we'll need to update the guide.mlh.io domain to point to
> gitbooks output.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/MLH/hackathon-organizer-guide/pull/34
> Commit Summary
>
>    - Create SUMMARY.md
>    - Create introduction.md
>    - Update SUMMARY.md
>    - Update introduction.md
>    - Delete README.md
>    - Delete SUMMARY.md
>    - Create SUMMARY.md
>    - Delete introduction.md
>    - Create introduction.md
>    - Update SUMMARY.md
>    - Update SUMMARY.md
>    - Create Organizer Timeline
>    - Update SUMMARY.md
>    - Update introduction.md
>    - Update SUMMARY.md
>    - removed files for gitbooks
>    - Delete .ruby-version
>    - Delete .ruby-gemset
>    - Delete .gitignore
>    - Create SUMMARY.md
>    - Create README.md
>    - Update SUMMARY.md
>    - Update README.md
>    - Update SUMMARY.md
>    - Update SUMMARY.md
>    - Update SUMMARY.md
>    - Update SUMMARY.md
>    - Update SUMMARY.md
>    - Create introduction.md
>    - Update SUMMARY.md
>    - Update README.md
>    - Update introduction.md
>    - Update SUMMARY.md
>    - Update index.md
>    - Update SUMMARY.md
>    - Update SUMMARY.md
>    - Added venue info.
>    - Updated Summary file.
>    - Removed Space.
>    - Added styling.
>    - Removed extra files.
>    - Updated URLs for conversion.
>    - Added 4 months prior.
>    - Added *.
>    - Converted 2 month prior
>    - Converted 1 Month prior.
>    - Converted for 1 week prior.
>    - Converted Day of Event.
>    - Removed Extra Images.
>    - Added closing info.
>    - Removed index file.
>
> File Changes
>
>    - *D* .gitignore
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-0>
>    (3)
>    - *D* .ruby-gemset
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-1>
>    (1)
>    - *D* .ruby-version
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-2>
>    (1)
>    - *D* Gemfile
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-3>
>    (5)
>    - *D* Gemfile.lock
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-4>
>    (126)
>    - *A* Organizer-Timeline/1-Month-Before/Create-Your-Schedule.md
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-5>
>    (37)
>    - *A* Organizer-Timeline/1-Month-Before/Finalize-Your-Emergency-Plan.md
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-6>
>    (19)
>    - *A* Organizer-Timeline/1-Month-Before/Headcount.md
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-7>
>    (3)
>    - *A* Organizer-Timeline/1-Month-Before/Organize-Transportation.md
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-8>
>    (68)
>    - *A* Organizer-Timeline/1-Month-Before/Supplies-And-Vendors.md
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-9>
>    (29)
>    - *A* Organizer-Timeline/1-Month-Before/Website.md
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-10>
>    (23)
>    - *A* Organizer-Timeline/1-Week-Before/Run-Through.md
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-11>
>    (43)
>    - *A* Organizer-Timeline/1-Week-Before/Send-Reminders.md
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-12>
>    (15)
>    - *A* Organizer-Timeline/2-Months-Before/Mentors-and-Judges.md
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-13>
>    (45)
>    - *A* Organizer-Timeline/2-Months-Before/Prizes.md
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-14>
>    (71)
>    - *A* Organizer-Timeline/2-Months-Before/Promote-Your-Event.md
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-15>
>    (63)
>    - *A* Organizer-Timeline/2-Months-Before/Website.md
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-16>
>    (11)
>    - *A* Organizer-Timeline/2-Months-Before/Workshops.md
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-17>
>    (9)
>    - *A* Organizer-Timeline/4-Months-Before/Become-a-MLH-Member-Event.md
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-18>
>    (31)
>    - *A*
>    Organizer-Timeline/4-Months-Before/Build-A-Killer-Leadership-Team.md
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-19>
>    (23)
>    - *A* Organizer-Timeline/4-Months-Before/Draft-Your-Budget.md
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-20>
>    (23)
>    - *A* Organizer-Timeline/4-Months-Before/Land-Sponsorships.md
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-21>
>    (9)
>    - *A* Organizer-Timeline/4-Months-Before/MLH-Sponsorship-Process.md
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-22>
>    (109)
>    - *A*
>    Organizer-Timeline/4-Months-Before/Set-Up-A-Placeholder-Website.md
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-23>
>    (35)
>    - *A* Organizer-Timeline/4-Months-Before/Sponsorship-Prospectus.md
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-24>
>    (29)
>    - *A* Organizer-Timeline/4-Months-Before/Understand-Your-Sponsors.md
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-25>
>    (49)
>    - *A* Organizer-Timeline/4-To-9-Months-Before/Venue.md
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-26>
>    (115)
>    - *A* Organizer-Timeline/After-The-Event.md
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-27>
>    (19)
>    - *A* Organizer-Timeline/Day-Of-Event/Kick-Off.md
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-28>
>    (21)
>    - *A* Organizer-Timeline/Day-Of-Event/Setup-Your-Event.md
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-29>
>    (91)
>    - *A* Organizer-Timeline/Day-Of-Event/Social-Media.md
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-30>
>    (7)
>    - *M* README.md
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-31>
>    (17)
>    - *A* SUMMARY.md
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-32>
>    (38)
>    - *D* _config.yml
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-33>
>    (18)
>    - *D* _includes/analytics.html
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-34>
>    (10)
>    - *D* _includes/head.html
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-35>
>    (20)
>    - *D* _includes/header.html
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-36>
>    (11)
>    - *D* _layouts/default.html
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-37>
>    (21)
>    - *D* _layouts/page.html
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-38>
>    (14)
>    - *D* _layouts/post.html
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-39>
>    (15)
>    - *D* _sass/_base.scss
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-40>
>    (209)
>    - *D* _sass/_layout.scss
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-41>
>    (237)
>    - *D* _sass/_syntax-highlighting.scss
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-42>
>    (67)
>    - *D* _sass/navbar.scss
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-43>
>    (61)
>    - *A* assets/fonts/outage.ttf
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-44>
>    (0)
>    - *A* assets/fonts/pacifico.ttf
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-45>
>    (0)
>    - *A* assets/images/miscellaneous/logos/mlh-standard.png
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-46>
>    (0)
>    - *A* assets/images/miscellaneous/logos/mlh-whitescale.png
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-47>
>    (0)
>    - *A* assets/images/miscellaneous/regions/europe.png
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-48>
>    (0)
>    - *A* assets/images/miscellaneous/regions/mexico.png
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-49>
>    (0)
>    - *A* assets/images/miscellaneous/regions/north-america.png
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-50>
>    (0)
>    - *A* assets/stylesheets/custom.css
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-51>
>    (74)
>    - *A* book.json
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-52>
>    (8)
>    - *A* closing.md
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-53>
>    (5)
>    - *D* css/main.scss
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-54>
>    (53)
>    - *D* feed.xml
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-55>
>    (30)
>    - *D* images/header-banner-small.png
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-56>
>    (0)
>    - *D* images/logos/dell-intel-logo.png
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-57>
>    (0)
>    - *D* images/logos/dell-logo.png
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-58>
>    (0)
>    - *D* images/logos/intel-logo.png
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-59>
>    (0)
>    - *D* images/logos/mlh-facebook.jpg
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-60>
>    (0)
>    - *D* images/logos/mlh-small-text-admin.png
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-61>
>    (0)
>    - *D* images/logos/mlh-small-text.png
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-62>
>    (0)
>    - *D* images/logos/mlh-small.png
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-63>
>    (0)
>    - *D* index.md
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-64>
>    (1077)
>    - *A* introduction.md
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-65>
>    (17)
>    - *R* layouts/footer.html
>    <https://github.com/MLH/hackathon-organizer-guide/pull/34/files#diff-66>
>    (5)
>
> Patch Links:
>
>    - https://github.com/MLH/hackathon-organizer-guide/pull/34.patch
>    - https://github.com/MLH/hackathon-organizer-guide/pull/34.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/MLH/hackathon-organizer-guide/pull/34>
>



-- 
CEO & Commissioner Emeritus, Major League Hacking
swift@mlh.io | (347) 391 4225 <+13473914225> | @SwiftAlphaOne
<https://twitter.com/SwiftAlphaOne>


[image: Inbox Status •]
<http://indicator.email/user/1ed89bb0-7197-11e4-b4ae-ffe363ba013f/>

**Comment by Shy** [comment]
Pushed a fix.

**Comment by bih** [comment]
This is almost done. Aiming to push into production by today, tomorrow by the latest.

**Comment by zachlatta** [comment]
:raised_hands:

**Comment by bih** [comment]
This has now gone live. See http://guide.mlh.io

I'm going to leave this open until the `gh-pages` branch has been deleted, this PR is closed and got a "LGTM" from @Shy in terms of anything needed from me. If you get the chance, it'd be nice just to test the webhook from the `master` branch of this repo and see if the guide is being updated as expected.

Overall, great job all! 👏  👏  👏   

screen shot 2016-05-04 at 14 04 31

**Comment by Shy** [comment]
LGTM

**Pull request closed without merging**
